name: crevasse
channels:
  - defaults
dependencies:
  - numpy
  - opencv
  - python=3.9
  - gdal
  - rasterio
  - scikit-learn
  - scikit-image
  - future
  - tensorflow=2.15
  - matplotlib
  - pydot
  - ipython
